version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:5000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python main.py"


